grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      dual: False
      penalty: l2
    search_param_grid:
      fit_intercept:
      - true
      - false

  module_1:
    class: SVC
    module: sklearn.svm
    params:
      probability: False
    search_param_grid:
      kernel:
      - rbf
      - sigmoid
      decision_function_shape:
      - ovr
      - ovo
